#!/usr/bin/env python

"""Return non-zero if an environment variable has not been set.

This script is used in tox.ini where shell constructs are not possible.

Usage:

    ensureenv VARIABLE-NAME
"""

from __future__ import absolute_import
from __future__ import print_function
from __future__ import unicode_literals

import os
import os.path
import sys


def main(argv=None):
    if argv is None:
        argv = sys.argv

    try:
        varname = argv[1]
    except IndexError:
        print("Usage: {} VARIABLE-NAME".format(os.path.basename(argv[0])),
              file=sys.stderr)

    if not os.getenv(varname):
        print("Missing required environment variable: {}".format(varname),
              file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
